### ISSUE TITLE
为什么缓存了之后，开飞行模式，再进app，显示的是问号，点击名字后却能拿到数据，执行的不都是getUserDetail方法吗

### ISSUE THREAD

**Issue by galileolvpo** [cpoopc/RetrofitRxCache#2]

**Comment by cpoopc** [comment]
#https://github.com/cpoopc/RetrofitRxCache/commit/c24a7ab85ad5f3142641ebee358699c4af87d210
看看这个commit

**Comment by galileolvpo** [comment]
这两个操作符看了下还不是很明白，回头还要再看看。不过简单来说好像就是 只要onNext 没有报错，就一定会按照onNext,onError/onComplete的这个顺序执行下去，解决了原来两个线程不好控制的问题，32个赞啊！！
