### ISSUE TITLE
导入aar的compile语句有问题

### ISSUE THREAD

**Issue by zengcanxiang** [cpoopc/RetrofitRxCache#3]
我使用md描述上面的compile语句的时候，发现找不到包。
看你的build.gradle配置文件和在JFrogBintray网站搜索，发现,你的项目名和版本号在三个地方都是不一样的。。
建议修改你的compile描述。在示例app程序里面，也可以不导入本地包，选择导入aar描述，这样的话，可以让人借鉴一下。
现在我也没导好包_(:зゝ∠)_

**Comment by zengcanxiang** [comment]
把jitpack.io引入之后，导进来了包，但是使用出错了。我排查之后发现是，我用的是比较新的rxjava和retrofit，cache用的是2.0beta的，建议升级了，毕竟是个beta版。_(:зゝ∠)_

**Comment by zengcanxiang** [comment]
把jitpack.io引入之后，导进来了包，但是使用出错了。我排查之后发现是，我用的是比较新的rxjava和retrofit，cache用的是2.0beta的，建议升级了，毕竟是个beta版。_(:зゝ∠)_

**Comment by cpoopc** [comment]
多谢提醒,之前觉得JitPack比较方便,就搬到JitPack上了,版本问题都没有留意到.
现在jitPack上版本升到v1.0.2了
支持retrofit 2.1.0了
